name: Slack alert for main, dev branch

on:
  push:
    branches: ["main"]

jobs:
  build:

    name: Slack_Alarm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      uses: actions/checkout@v2

      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,message,author # action,eventName,ref,workflow,job,took 추가할 수 있음
          mention: here
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.